### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by czi-frontend-infra** [chanzuckerberg/edu-design-system#1402]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] chore(deps): update all non-major dependencies (`@types/jest`, `@types/node`, `eslint`, `stylelint`, `yarn`)
 - [ ] chore(deps): update dependency @testing-library/react to v14
 - [ ] chore(deps): update dependency stylelint-config-recommended to v11
 - [ ] chore(deps): update dependency typescript to v5
 - [ ] 🔐 **Create all rate-limited PRs at once** 🔐

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [chore(deps): update prettier](../pull/1551) (`@chanzuckerberg/prettier-config-edu`, `eslint-config-prettier`)

## Detected dependencies

<details><summary>npm</summary>
<blockquote>

<details><summary>package.json</summary>

 - `@headlessui/react ^1.7.13`
 - `@popperjs/core ^2.11.6`
 - `@tippyjs/react ^4.2.6`
 - `clsx ^1.2.1`
 - `lodash.debounce ^4.0.8`
 - `react-beautiful-dnd ^13.1.1`
 - `react-children-by-type ^1.1.0`
 - `react-focus-lock ^2.9.4`
 - `react-popper ^2.3.0`
 - `react-portal ^4.2.2`
 - `@chanzuckerberg/axe-storybook-testing ^6.3.0`
 - `@chanzuckerberg/eslint-config-edu-js ^1.0.3`
 - `@chanzuckerberg/eslint-config-edu-ts ^1.0.7`
 - `@chanzuckerberg/eslint-plugin-edu-react ^1.1.9`
 - `@chanzuckerberg/eslint-plugin-stories ^3.2.12`
 - `@chanzuckerberg/prettier-config-edu ^1.0.3`
 - `@chanzuckerberg/story-utils ^3.0.12`
 - `@commitlint/cli ^17.4.4`
 - `@commitlint/config-conventional ^17.4.4`
 - `@geometricpanda/storybook-addon-badges ^1.1.1`
 - `@size-limit/file ^8.2.4`
 - `@storybook/addon-a11y ^6.5.16`
 - `@storybook/addon-docs ^6.5.16`
 - `@storybook/addon-essentials ^6.5.16`
 - `@storybook/addon-interactions ^6.5.16`
 - `@storybook/addon-links ^6.5.16`
 - `@storybook/addon-postcss ^2.0.0`
 - `@storybook/builder-webpack5 ^6.5.16`
 - `@storybook/manager-webpack5 ^6.5.16`
 - `@storybook/react ^6.5.16`
 - `@storybook/storybook-deployer ^2.8.16`
 - `@storybook/testing-library ^0.0.13`
 - `@storybook/testing-react ^1.3.0`
 - `@testing-library/jest-dom ^5.16.5`
 - `@testing-library/react ^13.4.0`
 - `@testing-library/user-event ^14.4.3`
 - `@types/jest ^29.4.0`
 - `@types/lodash.debounce ^4.0.7`
 - `@types/node ^18.15.0`
 - `@types/react ^18.0.28`
 - `@types/react-beautiful-dnd ^13.1.3`
 - `@types/react-dom ^18.0.11`
 - `@types/react-portal ^4.0.4`
 - `axe-core 4.6.3`
 - `chromatic ^6.17.1`
 - `codecov ^3.8.3`
 - `copyfiles ^2.4.1`
 - `eslint ^8.35.0`
 - `eslint-config-prettier ^8.6.0`
 - `eslint-plugin-jest ^27.2.1`
 - `eslint-plugin-prettier ^4.2.1`
 - `eslint-plugin-storybook ^0.6.11`
 - `eslint-plugin-testing-library ^5.10.2`
 - `husky ^8.0.3`
 - `identity-obj-proxy ^3.0.0`
 - `jest ^29.5.0`
 - `jest-environment-jsdom ^29.5.0`
 - `jest-preset-stylelint ^6.1.0`
 - `lint-staged ^13.2.0`
 - `pascal-case ^3.1.2`
 - `pinst ^3.0.0`
 - `plop ^3.1.2`
 - `postcss ^8.4.21`
 - `postcss-cli ^10.1.0`
 - `postcss-import ^15.1.0`
 - `postcss-mixins ^9.0.4`
 - `postcss-nested ^6.0.1`
 - `postcss-simple-vars ^7.0.1`
 - `prettier ^2.8.4`
 - `react ^18.2.0`
 - `react-dom ^18.2.0`
 - `size-limit ^8.2.4`
 - `snake-case ^3.0.4`
 - `standard-version ^9.5.0`
 - `storybook-css-modules-preset ^1.1.1`
 - `style-dictionary ^3.7.2`
 - `stylelint ^15.2.0`
 - `stylelint-config-recommended ^10.0.1`
 - `tailwindcss ^3.2.7`
 - `ts-jest ^29.0.5`
 - `typescript ^4.9.5`
 - `react >= 18`
 - `yarn 3.4.1`

</details>

</blockquote>
</details>

**Comment by booc0mtaco** [comment]
closing this to force the integration to review and re-create a similar ticket with the current dependencies

**Comment by jeremiah-clothier** [comment]
> closing this to force the integration to review and re-create a similar ticket with the current dependencies

Out of curiosity, what were you trying to do here? This PR should be updated every time the GitHub action workflow runs

**Comment by jeremiah-clothier** [comment]
> closing this to force the integration to review and re-create a similar ticket with the current dependencies

@booc0mtaco Out of curiosity, what were you trying to do here? This PR should be updated every time the GitHub action workflow runs

**Comment by jeremiah-clothier** [comment]
> @jeremiah-clothier at the time i wasn't sure what was causing the PRs to open, or how often so closed it to see what would happen as a test. Learned there must be something that is triggered on Mondays which reopened this way back when, and did another minor/patch bump

@booc0mtaco Gotcha! The schedule this runs on is here in you still need it https://github.com/chanzuckerberg/edu-design-system/blob/main/.github/workflows/update-dependencies.yml#L7
