### ISSUE TITLE
Use jscodeshift for adaptation of major versions

### ISSUE THREAD

**Issue by booc0mtaco** [chanzuckerberg/edu-design-system#1883]
## Request summary

When new major versions are released, there are often changes that require adapting the current code to the new constraints, component names, etc. Documenting the process is helpful, but could be even easier with codemods. 

An example is seen with the recent [v14](https://github.com/chanzuckerberg/edu-design-system/releases/tag/v14.0.0) version of EDS, where many components had some specific tweaks needed to upgrade.

## Relevant component(s)
What components this would affect.

- Any future components updated in major version releases.

## Example usage
An example, ideally in code, of how you want to use this feature.

**Comment by booc0mtaco** [comment]
https://github.com/facebook/jscodeshift

**Comment by jeremiah-clothier** [comment]
There's also this tool ts-morph which I may look into https://www.npmjs.com/package/ts-morph

**Comment by jeremiah-clothier** [comment]
Marking as closed

https://github.com/chanzuckerberg/edu-design-system/pull/1951 added an`eds-migrate` script which can be built on top of for future major version upgrades
