### ISSUE TITLE
Heading and Text should forward ref

### ISSUE THREAD

**Issue by anniehu4** [chanzuckerberg/edu-design-system#295]
## Request summary
Change Heading & Text to use `React.forwardRef`. 2 other options:
- accept a `ref` prop (a bit more annoying for end user b/c they have to type a unique prop name instead of just passing `ref`)
- use forwardRef with [`useImperativeHandle`](https://reactjs.org/docs/hooks-reference.html#useimperativehandle). @dcwither suggested this but I still don't fully understand it / whether it provides extra benefit for these type components

## Relevant component(s)
Heading, Text

## Example usage
Heading from traject:
```
<Heading
  headingRef={firstAction}
  onClick={() => setExpanded(prev => !prev)}
  size="h1"
  tabIndex={-1}
>
```

**Comment by anniehu4** [comment]
cc @dcwither @ahuth

**Comment by ahuth** [comment]
Woah, what's `useImperativeHandle` for? I'm not familiar with that one. Shouldn't be necessary to forward a ref to the component.

**Comment by dcwither** [comment]
I don't think forwardRef is necessary for this particular component though I think you had mentioned a scenario where people were trying to `focus()` on the `Heading`s in modals etc. in which case we should explore how much they need that vs. a possible work around.

I think it's more necessary for things like buttons etc. since they will need imperative function access like `focus()`.

**Comment by ahuth** [comment]
There are some use cases for focusing on a heading element.

For example, it's sort of ambiguous (as far as I know) whether modals should focus on the first focusable element or the heading element (although we tend to do the first focusable element in LP, which seems reasonable).

Also, LP is currently focusing on a heading in 1 case (that I know of) to work around limitations of the react-bootstrap button (we can't get a ref to the button in the version that we're on). So we may need this to have a smooth rollout.

I think it makes sense for heading (although maybe not with useImperitiveHandle. Still don't know what that does). And it could make sense to expose it for all "atom" components. Although that's a discussion for another time, perhaps.

**Comment by anniehu4** [comment]
yeah, this is the PR for context: https://github.com/FB-PLP/traject/pull/5025/files. It does seem we could remove this specific case once there's a non-bootstrap button...though I can imagine (because of modals, etc.) this might come up again for Headings, so I think it's worth adding

**Comment by dcwither** [comment]
I think [`useImperativeHandle`](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) allows us to say we're only exposing these functions from the ref, giving us a little more control. In our case, this may not be desired. I think it would also allow us to provide a more powerful interface if there were multiple elements that we needed to expose, say in the case of a dropdown where you want to expose functions from the menu and the button.

**Comment by anniehu4** [comment]
done in https://github.com/chanzuckerberg/edu-design-system/pull/452 & https://github.com/chanzuckerberg/edu-design-system/pull/457
