### ISSUE TITLE
Text should have an `as` or inline prop

### ISSUE THREAD

**Issue by dcwither** [chanzuckerberg/edu-design-system#299]
## Request summary
We should be able to control the tag for the text component to be something other than a `p` tag.

https://github.com/chanzuckerberg/edu-design-system/blob/master/packages/components/src/Text/Text.tsx

## Relevant component(s)
Text

## Example usage

```jsx
<Text as='span'>Inline Content</Text>
```
or 
```jsx
<Text inline>Inline Content</Text>
```

**Comment by anniehu4** [comment]
Done in https://github.com/chanzuckerberg/edu-design-system/pull/360
